name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows 11

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 33
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
